### ISSUE TITLE
大佬  有分时图吗？

### ISSUE THREAD

**Issue by 183883324** [xiesuichao/KLineView#12]

**Comment by WENGRUIGAN** [comment]
同求分时图

**Comment by xiesuichao** [comment]
不知道分时图长什么样，给我甩个UI，我来做，qq：181801034

**Comment by 183883324** [comment]
------------------ 原始邮件 ------------------
发件人: "Darren"<notifications@github.com>;
发送时间: 2019年6月4日(星期二) 下午3:15
收件人: "xiesuichao/KLineView"<KLineView@noreply.github.com>;
抄送: "183883324"<183883324@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xiesuichao/KLineView] 大佬  有分时图吗？ (#12)




不知道分时图长什么样，给我甩个UI，我来做，qq：181801034

**Comment by DARTTTTT** [comment]
> 不知道分时图长什么样，给我甩个UI，我来做，qq：181801034

大概就是由原来的蜡烛图变成线  也是收盘价
