### ISSUE TITLE
数据相同 不会绘制主蜡烛

### ISSUE THREAD

**Issue by huidtc** [xiesuichao/KLineView#14]
大神 当数据相同 蜡烛线就有空缺了这怎么修改一下

**Comment by icechao** [comment]
> 大神 当数据相同 蜡烛线就有空缺了这怎么修改一下

https://github.com/icechao/KlineChart 
试试这个  好用给个star

**Comment by xiesuichao** [comment]
什么数据相同会出现这种情况，我没试出来

**Comment by xiesuichao** [comment]
如果你是指的开盘价==收盘价，这个已解决，代码已提交。如果不是，再联系我
