### ISSUE TITLE
左右拖动时再向右拖动时  很难显示最右边的那个蜡烛图哟  要重新来回拖动几次

### ISSUE THREAD

**Issue by Jacko07** [xiesuichao/KLineView#16]
另外  如果收盘价等于开盘价 只会画一条竖线   下面是我的解决方法 大佬如果有更好的做法 可以更新哟

  float top = (float) (mMaxPriceY + (maxPrice - higherPrice) * avgHeightPerPrice);
            float bottom=(float) (mMaxPriceY + (maxPrice - lowerPrice) * avgHeightPerPrice);
            if (top == bottom)
            { //如果不做此判断 则 会出现只有竖线的情况
                bottom = (float)( top - 1);
            }
            //priceRect
            canvas.drawRect((float) viewDataList.get(i).getLeftX() + dp2px(0.5f),
                    top,
                    (float) viewDataList.get(i).getRightX() - dp2px(0.5f),
                    bottom,
                    fillPaint);

**Comment by xiesuichao** [comment]
左右滑动不显示最右边那条数据的bug已解决。
收盘价==开盘价，这个已按你的方式改了，人为给1px的高度。不过坐标系是从上到下的，bottom = top + 1 比较合理一点。
代码已提交
