### ISSUE TITLE
我用demo 滑动带最有 ma 图 变成一条线了

### ISSUE THREAD

**Issue by ousq** [xiesuichao/KLineView#18]
![image](https://user-images.githubusercontent.com/18591884/79037320-74d33900-7c02-11ea-8214-d0a58884be6c.png)
还是数据一一样导致的

**Comment by ousq** [comment]
![image](https://user-images.githubusercontent.com/18591884/79037335-8a486300-7c02-11ea-944c-e3de83a604eb.png)

**Comment by xiesuichao** [comment]
demo里模拟的数据相差幅度太大导致的
