### ISSUE TITLE
怎么像火币那样添加游标指示

### ISSUE THREAD

**Issue by alizhijun** [xiesuichao/KLineView#19]
火币K线里面最右边会有个游标,根据价格上下浮动

**Comment by xiesuichao** [comment]
可以照着里面的十字线的逻辑写，我这里等抽出空再来加这个需求

**Comment by DARTTTTT** [comment]
> 火币K线里面最右边会有个游标,根据价格上下浮动

在刻度线那里可以自己加个方法

**Comment by DARTTTTT** [comment]
> 火币K线里面最右边会有个游标,根据价格上下浮动

 //横坐标
    private void drawAbscissa(Canvas canvas) {
        resetFillPaint(abscissaTextCol, abscissaTextSize);
        for (int i = 0; i < verticalXList.size(); i++) {
            if (i == 0 && viewDataList.get(0).getLeftX() <= verticalXList.get(0) + avgPriceRectWidth / 2
                    && viewDataList.get(0).getRightX() > verticalXList.get(0)) {
                canvas.drawText(formatDate(viewDataList.get(0).getTime()),
                        leftStart + dp2px(6),
                        bottomEnd - dp2px(7),
                        fillPaint);

            } else if (i == verticalXList.size() - 1) {
                String dateStr = formatDate(viewDataList.get(viewDataList.size() - 1).getTime());
                canvas.drawText(dateStr,
                        rightEnd - dp2px(41) - fillPaint.measureText(dateStr),
                        bottomEnd - dp2px(7),
                        fillPaint);
            } else {
                for (KData data : viewDataList) {
                    if (data.getLeftX() <= verticalXList.get(i) && data.getRightX() >= verticalXList.get(i)) {
                        String dateStr = formatDate(data.getTime());
                        canvas.drawText(dateStr,
                                verticalXList.get(i) - fillPaint.measureText(dateStr) / 2,
                                bottomEnd - dp2px(7),
                                fillPaint);
                        break;
                    }
                }
            }
        }


        //实时价格的标签
        if (lastKData != null) {
            double moveY = lastKData.getCloseY();
            RectF blueRectF = new RectF(rightEnd - dp2px(38),
                    (float) moveY - dp2px(7),
                    rightEnd - dp2px(1),
                    (float) moveY + dp2px(7));
            //根据涨跌设置标签颜色
            if (lastKData.getUpDnAmount() > 0) {
                fillPaint.setColor(priceIncreaseCol);
            } else {
                fillPaint.setColor(priceFallCol);
            }
            canvas.drawRoundRect(blueRectF, 4, 4, fillPaint);
            curvePath.reset();
            curvePath.moveTo(verticalXList.get(verticalXList.size() - 1), (float) moveY);
            curvePath.lineTo(rightEnd - dp2px(37), (float) moveY - dp2px(3));
            curvePath.lineTo(rightEnd - dp2px(37), (float) moveY + dp2px(3));
            curvePath.close();
            canvas.drawPath(curvePath, fillPaint);
            String movePrice = String.valueOf(lastKData.getClosePrice());//直接是收盘价
            Rect textRect = new Rect();
            resetFillPaint(crossHairRightLabelTextCol, crossHairRightLabelTextSize);
            fillPaint.getTextBounds(movePrice, 0, movePrice.length(), textRect);
            canvas.drawText(movePrice,
                    rightEnd - dp2px(38) + (blueRectF.width() - textRect.width()) / 2,
                    (float) moveY + dp2px(7) - (blueRectF.height() - textRect.height()) / 2,
                    fillPaint);

        }

    }

**Comment by DARTTTTT** [comment]
> > 火币K线里面最右边会有个游标,根据价格上下浮动
> 
> 在横坐标那里可以自己加个方
