### ISSUE TITLE
如果把底部的柱状图去掉的话麻烦吗 volme

### ISSUE THREAD

**Issue by enjian971221** [xiesuichao/KLineView#27]

**Comment by xiesuichao** [comment]
稍微有点，只要主图和副图，不要数量是吗

**Comment by enjian971221** [comment]
priceImgBot = horizontalYList.get(5);
            volumeImgBot = horizontalYList.get(5);我是把默认显示的底部的柱状图去掉了，附图也没要

**Comment by xiesuichao** [comment]
好的，那你自己调整一下
