### ISSUE TITLE
请教 怎么加分时图

### ISSUE THREAD

**Issue by 1825492258** [xiesuichao/KLineView#3]
有分时图的demo嘛

**Comment by xiesuichao** [comment]
分时图我之前考虑的是重新向后台请求数据，然后调initKDataList方法。后来想了一下，在本地也可以做。这个功能本周末应该能做好，到时候提交一下

**Comment by xiesuichao** [comment]
切换时间单位时，重新调接口请求数据，然后调resetDataList方法重置数据
