### ISSUE TITLE
调用resetDataList后，没有定位到最右边，也就是最新数据的位置

### ISSUE THREAD

**Issue by clj12081103** [xiesuichao/KLineView#7]
我在1m,5m,15m  k线之间切来切去，就会出现这个问题

**Comment by xiesuichao** [comment]
目前resetDataList方法里做的是，左边起点定位在reset之前的那个时间点，比如：滑到一个月之前，到9月30号了，切换了之后，拿到的数据集合里包含9月30号的，就会定位到9月30号开始进行显示。如果没有9月30号，就定位到最右边。这个功能目前还在考虑要不要保留，17号我修改完提交一下，今天和明天没有时间

**Comment by xiesuichao** [comment]
最近被事情耽搁了，resetDataList方法已修改，可自行传入boolean值决定是否需要将新数据定位到之前的时间点，详情见方法注释
