### ISSUE TITLE
你好，有个小小的建议

### ISSUE THREAD

**Issue by q876625596** [xiesuichao/KLineView#8]
我下载了demo看了一下，发现在滑动的时候是按照每一个小的item作为单位滑动的，这样就会给人一种帧数很低的错觉，我想问问可不可以将滑动弄成连续顺滑的，感官效果更好一点

**Comment by xiesuichao** [comment]
这个可以做，之前考虑过，改动有点大，挺麻烦的，我找个时间再做吧

**Comment by WENGRUIGAN** [comment]
有联系方式吗 ？我发现这个布局只能设置固定的宽高  ，如果设置为权重比就不会显示

**Comment by xiesuichao** [comment]
改动太大，暂时不考虑了
